### ISSUE TITLE
Unable to enter a world when used with Quark 1.18

### ISSUE THREAD

**Issue by xiaoschannel** [baguchan/TofuCraftReload-Recode#3]
Also reporting this in Quark
https://github.com/VazkiiMods/Quark/issues/3506

Minimal procedure to reproduce:
TofuCraftReload-1.18.1-0.7.0
Quark-3.0-332
Forge 39.0.8
(Create new world to reproduce)

[Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because the return value of "net.minecraft.world.item.crafting.Recipe.m_8043_()" is null[Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because the return value of "net.minecraft.world.item.crafting.Recipe.m_8043_()" is null Index: 4 Listeners: 0: NORMAL 1: net.minecraftforge.eventbus.EventBus$$Lambda$4197/0x0000000800b773c8@6fe5ddc1 2: ASM: net.minecraftforge.common.ForgeInternalHandler@34fd35ea playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V 3: ASM: class baguchan.tofucraft.CommonEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V 4: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@584e32d8 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)Vjava.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because the return value of "net.minecraft.world.item.crafting.Recipe.m_8043_()" is null at TRANSFORMER/quark@3.0-332/vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule.lambda$onPlayerLoggedIn$0(AutomaticRecipeUnlockModule.java:53) at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672) at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660) at TRANSFORMER/quark@3.0-332/vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule.onPlayerLoggedIn(AutomaticRecipeUnlockModule.java:53) at net.minecraftforge.eventbus.ASMEventHandler_152_AutomaticRecipeUnlockModule_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) at TRANSFORMER/forge@39.0.8/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:810) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:237) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:229) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) at java.base/java.lang.Thread.run(Thread.java:833)
[10:22:21] [Server thread/ERROR]: Couldn't place player in worldjava.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because the return value of "net.minecraft.world.item.crafting.Recipe.m_8043_()" is null at vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule.lambda$onPlayerLoggedIn$0(AutomaticRecipeUnlockModule.java:53) ~[Quark-3.0-332.jar%2353!:3.0-332] at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?] at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?] at vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule.onPlayerLoggedIn(AutomaticRecipeUnlockModule.java:53) ~[Quark-3.0-332.jar%2353!:3.0-332] at net.minecraftforge.eventbus.ASMEventHandler_152_AutomaticRecipeUnlockModule_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:810) ~[forge-1.18.1-39.0.8-universal.jar%2359!:?] at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:237) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.network.Connection.m_129483_(Connection.java:229) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2355!:?] at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by baguchi** [comment]
It will fixed for newer quark versions
